ARL: false
ARL_n: 1
BT: null
BTObj: null
DyBT: null
DyBTObj: null
DyBTalpha: 0.1
DyBTinit: original
FCL: false
FCLObj: g
GBT: false
GBTObj: null
GBT_N: null
GBT_alpha: 1
INLP: false
INLP_by_class: false
INLP_discriminator_reweighting: null
INLP_min_acc: 0.0
INLP_n: 300
activation_function: ReLu
adv_BT: null
adv_BTObj: null
selection_criterion: DTO
adv_activation_function: ReLu
adv_batch_norm: false
adv_batch_size: 1024
adv_checkpoint_interval: 1
adv_corr_loss: false
adv_debiasing: true
adv_decoupling: false
adv_decoupling_labelled_proportion: 1.0
adv_diverse_lambda: 5.0
adv_dropout: 0.1
adv_epochs: 100
adv_epochs_since_improvement: 5
adv_gated: false
adv_gated_mapping: null
adv_gated_type: Augmentation
adv_hidden_size: 256
adv_lambda: 1.5
adv_level: last_hidden
adv_lr: 0.1
adv_n_hidden: 2
adv_num_subDiscriminator: 3
adv_test_batch_size: 1024
adv_uniform_label: false
adv_update_frequency: Batch
base_seed: 1
batch_norm: false
batch_size: 1024
checkpoint_interval: 1
classification_head_update_frequency: 1
conf_file: null
data_dir: /home/user/miniconda3/data/compass
dataset: COMPAS_race
device_id: 0
dropout: 0.1
emb_size: 400
encoder_architecture: DecreasingNN
epochs: 100
epochs_since_improvement: 10
exp_id: vanilla
f: null
fcl_base_temperature_g: 0.01
fcl_base_temperature_y: 0.01
fcl_lambda_g: 0.1
fcl_lambda_y: 0.1
fcl_temperature_g: 0.01
fcl_temperature_y: 0.01
full_label: true
gated: false
gated_mapping: null
log_file: ./results/dev/compass/test/output.log
log_interval: 50
log_level: INFO
lr: 0.1
model_dir: ./results
n_bins: 4
n_hidden: 5
hidden_size: 4
no_log: false
num_classes: 2
num_groups: 3
num_workers: 0
project_dir: dev
protected_task: race
regression: false
results_dir: ./results/
save_batch_results: false
save_models: false
test_batch_size: 1024
weight_decay: 0.7
softmax: false
